Improves documentation and fixes small bug
ctsit/mobile_api_request_to_survey pull request #7
Opened 2018-07-05 19:55 UTC by marlycormar

### Overview:
- Targets issue #6.
- Fixes bug:  if the descriptive text was left blank, the word *null* would show up on the token request page.

(Thanks @tlstoffs for making corrections to the workflow section on the `README.md`)

2018-07-25 19:17 UTC, pbchase requested changes
The README could use just a few more changes. See my notes.

2018-07-25 19:17 UTC, pbchase commented on README.md
> +4. The project manager/administrator disables the module: The project manager/administrator disables the module in the project by going to the ** External Modules** page (under Applications) and clic
we must be clear about where the module disable event occurs.  Maybe the title for this bullet should read `The project manager/administrator disables the module at the project level`.  Then add emphasis in the sentence.  Maybe like this:

```
The project manager/administrator disables the module level: The project manager/administrator disables the module in the _project_ by going to the **External Modules** page (under Applications) and clicking **Disable** next to the **Route Mobile Api Token Requests to Survey** module.
```

2018-07-25 19:17 UTC, pbchase commented on README.md
> +5. The user goes back to the project in question and clicks the **Request API token** button on the **REDCap Mobile App** page.
I think step 5 needs to be preceded by a new step that reads something like this

```
The project manager/administrator contacts the user: The project manager/administrator sends a message to the user asking him to revisit the mobile API token request page to complete the token request.
```

2018-07-27 19:29 UTC, marlycormar commented
@pbchase, thanks for the input. I made improvements in the README.md based on your comments. Could you please review them?

2018-07-30 21:00 UTC, pbchase commented
Looks good.  I'll merge!

2018-07-30 21:00 UTC, merged